import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface ChangesetConfig {
  changelog: unknown;
  commit: boolean;
  fixed: Array<unknown>;
  linked: Array<unknown>;
  access: 'public' | 'restricted';
  baseBranch: string;
  updateInternalDependencies: 'patch' | 'minor';
  ignore: Array<string>;
}

interface PackageJson {
  scripts?: Record<string, string>;
  [key: string]: unknown;
}

export interface ChangesetInitOptions {
  cwd?: string;
  access?: 'public' | 'restricted';
  baseBranch?: string;
}

/**
 * Initializes a changeset setup in the specified directory.
 *
 * Creates a `.changeset` directory with a default configuration and README if they do not already exist. The configuration file is customized based on the provided options.
 *
 * @param options - Optional settings to specify the working directory, access level, and base branch for the changeset configuration.
 *
 * @throws {Error} If file system operations fail during initialization.
 */
export function initChangesets(options: ChangesetInitOptions = {}): void {
  const {
    cwd = process.cwd(),
    access = 'public',
    baseBranch = 'main',
  } = options;

  try {
    // Create .changeset directory
    const changesetDir = join(cwd, '.changeset');
    if (!existsSync(changesetDir)) {
      mkdirSync(changesetDir, { recursive: true });
    }

    // Copy default config
    const configSource = join(dirname(__dirname), 'config', 'config.json');
    const configTarget = join(changesetDir, 'config.json');

    if (!existsSync(configTarget)) {
      // Read and modify config based on options
      const config = JSON.parse(
        readFileSync(configSource, 'utf8')
      ) as ChangesetConfig;
      config.access = access;
      config.baseBranch = baseBranch;

      writeFileSync(configTarget, JSON.stringify(config, null, 2) + '\n');
      console.log('✓ Created changeset config');
    }

    // Create README
    const readmePath = join(changesetDir, 'README.md');
    if (!existsSync(readmePath)) {
      const readmeContent = `# Changesets

Hello and welcome! This folder has been automatically generated by \`@changesets/cli\`, a build tool that works
with multi-package repos, or single-package repos to help you version and publish your code. You can
find the full documentation for it [in our repository](https://github.com/changesets/changesets)

We have a quick list of common questions to get you started engaging with this project in
[our documentation](https://github.com/changesets/changesets/blob/main/docs/common-questions.md)
`;
      writeFileSync(readmePath, readmeContent);
      console.log('✓ Created changeset README');
    }

    console.log('✓ Changesets initialized successfully');
  } catch (error) {
    console.error('Failed to initialize changesets:', error);
    throw error;
  }
}

/**
 * Adds standard changeset scripts to a package.json file if they do not already exist.
 *
 * @param packageJsonPath - Optional path to the package.json file. Defaults to the package.json in the current working directory.
 *
 * @remark
 * The function updates the file in place and logs whether scripts were added or already present.
 *
 * @throws {Error} If reading, parsing, or writing the package.json file fails.
 */
export function addChangesetScripts(packageJsonPath?: string): void {
  const pkgPath = packageJsonPath ?? join(process.cwd(), 'package.json');

  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as PackageJson;

    pkg.scripts ??= {};

    const scripts = {
      changeset: 'changeset',
      'changeset:version': 'changeset version',
      'changeset:publish': 'changeset publish',
    };

    let added = false;
    for (const [name, command] of Object.entries(scripts)) {
      if (!pkg.scripts[name]) {
        pkg.scripts[name] = command;
        added = true;
      }
    }

    if (added) {
      writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
      console.log('✓ Added changeset scripts to package.json');
    } else {
      console.log('ℹ Changeset scripts already exist');
    }
  } catch (error) {
    console.error('Failed to add changeset scripts:', error);
    throw error;
  }
}
