# Bun configuration for @outfitter/monorepo
# https://bun.sh/docs/runtime/configuration

[install]
# Match pnpm's behavior for workspace packages
linkWorkspacePackages = true

# Use exact versions for lockfile stability
exact = false

# Cache configuration
cache = true
registry = "https://registry.npmjs.org"

# Optional: configure global directories
# globalDir = "~/.bun/install/global"
# globalBinDir = "~/.bun/bin"

[install.scopes]
# Optimize for our common scopes
"@outfitter" = { registry = "https://registry.npmjs.org" }
"@biomejs" = { registry = "https://registry.npmjs.org" }
"@changesets" = { registry = "https://registry.npmjs.org" }

[test]
# Default test configuration
preload = ["./shared/testing/vitest.config.base.ts"]
coverage = true
timeout = 10000

[run]
# Set NODE_ENV if not already set
env = { NODE_ENV = "development" }

[dev]
# Enable hot reloading for development
hot = true